build:
  environment:
    php:
      version: "7.1"

  nodes:
    tests:
      tests:
        override:
        -
          command: vendor/bin/phpunit --coverage-clover /tmp/coverage.xml
          coverage:
            file: /tmp/coverage.xml
            format: clover

    analysis:
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true

filter:
  dependency_paths:
    - "propel/"

  excluded_paths:
    - "app/"
    - "config/"
    - "bin/"
    - "storage/"
    - "tests/"
    - "vendor/"
